project_id = "ixniqsugotfpaesjntkx"

[functions.protect-pdf]
verify_jwt = false

[functions.unlock-pdf]
verify_jwt = false

[functions.analyze-document]
verify_jwt = false

[functions.sign-pdf]
verify_jwt = false
